### ISSUE TITLE
empty notes aren't saved or deleted

### ISSUE THREAD

**Issue by ohspite** [sidenotes/sidenotes#77]
Hi, and thanks for making the great extension.  

If you create a side note with some content, wait for it to save, and then delete the content, then the deletion is not saved.  Closing the sidenote panel and then opening it again shows the text that was entered before the last sync.  

If this isn't a desired feature, it looks like the change could be made to background.js line 207 which checks for a nonempty body:

`if(changes[hashKey]['newValue'] && changes[hashKey]['newValue']['url'] && changes[hashKey]['newValue']['body'])`

Alternatively, and maybe better, if the body is empty then the note could be deleted with a variation of `datastoreController.deleteNote` that does not require user confirmation.

**Comment by darzo27** [comment]
@stefankp I didn't want to create a new issue so here goes: I thoroughly _enjoyed_ the app, pity.. I checked my sideNotes folder on dropbox and it was cleared, does that mean with them retiring the DataStore API they immediately revoke any store access by an app as well as clear it's storage? It's quite a bummer since I has well over 200 notes there for websites & useful content which I never bookmarked.. yet. @n-zeplo @jcsalaza @nickgio

**Comment by stefankp** [comment]
@ohspite Thank you for pointing that out. However we have seized development on Sidenotes, so there will be no more updates. The code is open source, you can of course use it for your own version. 

@darzo27 It's not possible to access the Datastores on Dropbox anymore. Actually, that folder has always been empty, because the Datastores are not saved in files. However, all your notes are also saved in Chrome's Local Storage. So if you haven't cleaned your Browser data, your notes are still there. However, I am sorry to say that I don't know how to access _all_ your local storage, because it's based on each domain.
